-- Adiciona colunas f06-f14 na fichas_anomalias_cache
-- (flag_f13 já existe — só adiciona as que faltam)

ALTER TABLE db_ressarcimento.fichas_anomalias_cache
  ADD COLUMN IF NOT EXISTS flag_f06  TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS flag_f07  TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS flag_f08  TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS flag_f09  TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS flag_f10  TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS flag_f11  TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS flag_f12  TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS flag_f14  TINYINT(1) NOT NULL DEFAULT 0;
